name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.15.2
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Package Extension
        run: pnpm run package
      - name: Get version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          SHORT_HASH=$(git rev-parse --short HEAD)
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
          echo "release_name=v${VERSION}-${SHORT_HASH}" >> $GITHUB_OUTPUT
      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./recline-*.vsix
          file_glob: true
          tag: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.release_name }}
          overwrite: true
